'use client';
// import type { Metadata } from "next";

import StyledComponentsRegistry from '@/lib/registry';
import { ThemeProvider } from 'styled-components';
import LightTheme from '@/themes/lightTheme';
import GlobalStyle from './GlobalStyle.styled';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <StyledComponentsRegistry>
      <GlobalStyle />
      <html lang="es">
        <body>
          <ThemeProvider theme={LightTheme}>{children}</ThemeProvider>
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
